/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Database {
  lastFetch: number;
  data: Character[];
}
export interface Character {
  characterId: number;
  name: string;
  class: number;
  element: number;
  grade: number;
  portraitUrl: string;
  mainBuild1Name: string;
  mainBuild1Desc: string;
  mainBuild2Name: string;
  mainBuild2Desc?: string;
  supportBuild1Name: string;
  supportBuild1Desc: string;
  supportBuild2Name: string;
  supportBuild2Desc: string;
  potentials: Potential[];
}
export interface Potential {
  id: number;
  name: string;
  descShort: string;
  descLong: string;
  rarity: number;
  build: number;
  type: number;
}
